### ISSUE TITLE
 Error: Menu.Element/menu.ctp 

### ISSUE THREAD

**Issue by KubqoA** [QoboLtd/cakephp-qobo-admin-panel#47]
I followed the guide to install this plugin and now when I open my CakePHP project only error comes up. I put the screenshot of it here. [Screenshot](http://prnt.sc/c72ht2) If you can help me it would be awesome I like the design you used and I would really like to use it.

**Comment by mamchenkov** [comment]
Hi,

it looks like our documentation got a little bit outdated :) We'll update it shortly and release a new version.  Gives us an hour or so.

**Comment by KubqoA** [comment]
Okay thank you. Then tell me when it's fixed :)

**Comment by mamchenkov** [comment]
Hi,

we've updated the documentation a bit, which should help you solve the issue.  Have a look at [this pull request](https://github.com/QoboLtd/cakephp-qobo-admin-panel/pull/48).

Please let us know if this resolved the issue.

**Comment by mamchenkov** [comment]
@KubqoA Did you manage to resolve your problem?  Can we close this issue?

**Comment by mamchenkov** [comment]
Closing the issue. :)  Please reopen if the problem still persists.
